import time
from typing import Any, Literal, NamedTuple, Protocol, Sequence, cast

import jax
import numpy as np

# from tokenizers import Tokenizer
from distrax import Categorical
from flax import nnx
from jax import numpy as jnp
from rich.console import Console
from rich.markdown import Markdown
from transformers import BatchEncoding, PreTrainedTokenizerFast
from vaml.config import SamplingConfig
from vaml.model import Qwen3
from vaml.util import batched_put_where, batched_take

# these should come from the tokenizer
STOP_TOKEN = 151645

class GenerationState(NamedTuple):
    kv_cache: Any

    # where the model is in the context in term of evaluation
    kv_cache_length: jax.Array
    # how long the context is
    context_length: jax.Array
    # this indicates where the prompt turn ends and the conversation turn starts
    turn_start_positions: jax.Array
    # true for prompt tokens and false for tokens generated by the model
    policy_mask: jax.Array
    # tokens for the context, this includes both prompts and generated tokens
    context: jax.Array

    # gen variables
    turn_finished: jax.Array
    rng_key: jax.Array

    # rollout
    log_probs: jax.Array
    values: jax.Array

    # metrics
    tokens_processed: jax.Array


class NpGenData(NamedTuple):
    kv_cache_length: np.ndarray
    context: np.ndarray
    log_probs: np.ndarray
    values: np.ndarray
    policy_mask: np.ndarray
    context_length: np.ndarray
    turn_start_positions: np.ndarray
    turn_finished: np.ndarray


def convert_to_np(gen: GenerationState) -> NpGenData:
    data = (
        gen.kv_cache_length,
        gen.context,
        gen.log_probs,
        gen.values,
        gen.policy_mask,
        gen.context_length,
        gen.turn_start_positions,
        gen.turn_finished,
    )
    return NpGenData(*jax.tree.map(lambda x: np.array(x), jax.device_get(data)))


def update_gen_state(gen: GenerationState, update: NpGenData) -> GenerationState:
    context, kv_cache_length, context_length, turn_start_positions = jax.device_put(
        (
            update.context,
            update.kv_cache_length,
            update.context_length,
            update.turn_start_positions,
        )
    )
    return gen._replace(
        context=context,
        turn_start_positions=turn_start_positions,
        context_length=context_length,
        kv_cache_length=kv_cache_length,
        turn_finished=jnp.zeros_like(gen.turn_finished),
    )


class ResponseData(Protocol):
    context: Any
    context_length: Any
    turn_start_positions: Any
    turn_finished: Any


def encode_input(
    tokenizer: PreTrainedTokenizerFast,
    conversations: list[list[dict]],
    add_generation_prompt=True,
) -> list[np.ndarray]:
    return cast(
        list[np.ndarray],
        tokenizer.apply_chat_template(
            conversations,
            add_generation_prompt=add_generation_prompt,
            return_dict=False,
            return_tensors="np",
        ),
    )


def decode_responses(
    tokenizer: PreTrainedTokenizerFast,
    gen: ResponseData,
) -> tuple[np.ndarray, list[str]]:
    (indices,) = np.where(gen.turn_finished)
    indices = indices.astype(np.int32)

    context = np.asarray(gen.context)
    turn_start_positions = np.asarray(gen.turn_start_positions)
    context_length = np.asarray(gen.context_length)

    output = cast(
        list[str],
        [
            tokenizer.decode(
                context[b, turn_start_positions[b] : context_length[b] - 1]
            )
            for b in indices
        ],
    )

    return indices, output


def sample(config: SamplingConfig, logits, rng_key):
    V = logits.shape[-1]
    k = min(config.top_k, V)

    topk_logits, topk_idx = jax.lax.top_k(logits, k)  # (..., k)
    topk_logits = topk_logits / config.temperature

    topk_probs = jax.nn.softmax(topk_logits, axis=-1)  # (..., k)

    cumsum = jnp.cumsum(topk_probs, axis=-1) - topk_probs
    masked_topk_logits = jnp.where(cumsum < config.top_p, topk_logits, -jnp.inf)

    sample_in_topk = jax.random.categorical(rng_key, masked_topk_logits, axis=-1)
    sample_in_topk = jnp.expand_dims(sample_in_topk, axis=-1)
    sampled_ids = jnp.take_along_axis(topk_idx, sample_in_topk, axis=-1).squeeze(-1)

    return sampled_ids


def create_generation_state(
    kv_cache, batch_size: int, seq_len: int, rng_key: jax.Array
) -> GenerationState:
    return GenerationState(
        kv_cache=kv_cache,
        kv_cache_length=jnp.zeros(batch_size, jnp.int32),
        context_length=jnp.zeros(batch_size, jnp.int32),
        turn_start_positions=jnp.zeros(batch_size, jnp.int32),
        policy_mask=jnp.zeros((batch_size, seq_len), jnp.bool_),
        context=jnp.zeros((batch_size, seq_len), jnp.int32),
        turn_finished=jnp.zeros((batch_size,), jnp.bool_),
        log_probs=jnp.zeros((batch_size, seq_len - 1), jnp.float32),
        values=jnp.zeros((batch_size, seq_len), jnp.float32),
        rng_key=rng_key,
        tokens_processed=jnp.zeros((), dtype=jnp.int32),
    )


# state should be NpGenData
def append_prompt_tokens(
    state, batch_indices: np.ndarray, prompts: np.ndarray | Sequence[np.ndarray]
):
    for i, prompt in zip(batch_indices, prompts):
        start = state.context_length[i].item()
        end = start + prompt.shape[0]
        safe_end = min(end, state.context.shape[1])
        if safe_end < end:
            delta = end - safe_end
            prompt = prompt[:-delta]

        state.context[i, start:safe_end] = prompt

        state.turn_start_positions[i] = safe_end
        state.context_length[i] = safe_end

    return state


# state should be NpGenData
def append_user_prompts(
    state,
    batch_indices: np.ndarray,
    tokenizer: PreTrainedTokenizerFast,
    prompts: list[str],
):
    conversation_turns = [[{"role": "user", "content": content}] for content in prompts]
    prompt_tokens = encode_input(tokenizer, conversation_turns)

    append_prompt_tokens(state, batch_indices, prompt_tokens)


@jax.jit(
    static_argnames=("model_def", "sampling", "wait_for"),
    donate_argnames=("gen",),
)
def generate(
    model_def,
    model_state,
    sampling: SamplingConfig | Literal["greedy", "simple"],
    gen: GenerationState,
    wait_for: int = 1,
) -> GenerationState:
    model = nnx.merge(model_def, model_state)

    B, seq_length = gen.context.shape

    def cond(carry: GenerationState):
        # todo: this could infinite loop
        return jnp.sum(carry.turn_finished) < wait_for

    def body(carry: GenerationState):
        in_tokens = batched_take(carry.context, carry.kv_cache_length)

        logits, value_repr, kv_cache, rng_key = model(
            in_tokens[..., None],  # add time axis
            carry.kv_cache_length[..., None],
            carry.kv_cache,
            rng_key=carry.rng_key,
        )
        logits = logits.squeeze(-2)  # remove time axis
        # value = model.get_value(value_repr).squeeze(-1)

        rng_key, sample_key = jax.random.split(rng_key)
        dist = Categorical(logits=logits)
        sample_tokens: jax.Array = dist.sample(seed=sample_key)
        log_prob = cast(jax.Array, dist.log_prob(sample_tokens))

        # store everything
        over_start_position = carry.kv_cache_length + 1 >= carry.turn_start_positions
        turn_finished = carry.turn_finished | (carry.kv_cache_length + 2 >= seq_length)
        use_sample = ~turn_finished & over_start_position

        kv_cache_length = jnp.where(
            turn_finished, carry.kv_cache_length, carry.kv_cache_length + 1
        )
        context_length = jnp.where(
            turn_finished,
            carry.context_length,
            jnp.maximum(carry.context_length, carry.kv_cache_length + 2),
        )

        context = batched_put_where(
            carry.context, kv_cache_length, sample_tokens, use_sample
        )
        log_probs = batched_put_where(
            carry.log_probs, carry.kv_cache_length, log_prob, use_sample
        )
        # we want to track values even for prompt tokens, hence no use_sample check
        # values = batched_put_where(
        #     carry.values, carry.kv_cache_length, value, ~turn_finished
        # )

        # we might be able to drop the ~turn_finished filter here
        policy_mask = batched_put_where(
            carry.policy_mask, carry.kv_cache_length, use_sample, ~turn_finished
        )

        tokens_processed = carry.tokens_processed + jnp.sum(~turn_finished)

        turn_finished = turn_finished | ((in_tokens == STOP_TOKEN) & over_start_position)

        return carry._replace(
            kv_cache=kv_cache,
            kv_cache_length=kv_cache_length,
            context_length=context_length,
            context=context,
            turn_finished=turn_finished,
            log_probs=log_probs,
            # values=values,
            policy_mask=policy_mask,
            rng_key=rng_key,
            tokens_processed=tokens_processed,
        )

    return nnx.while_loop(cond, body, gen)


def chat(
    console: Console,
    model: Qwen3,
    tokenizer,
    sampling,
    batch_size: int,
    seq_length: int,
    rngs: nnx.Rngs,
    *,
    system_prompt: str | None = None,
):
    kv_cache = model.initialize_carry(batch_size, seq_length)
    model_def, model_state = nnx.split(model)

    gen = create_generation_state(kv_cache, batch_size, seq_length, rngs.sample())
    np_gen = convert_to_np(gen)

    batch_indices = np.arange(batch_size, dtype=np.int32)

    # if system_prompt is not None:
    #     text = [
    #         [{"role": "system", "content": system_prompt}] for _ in range(batch_size)
    #     ]
    #     prompt_tokens = encode_input(tokenizer, text, add_generation_prompt=False)
    #     gen = append_prompt_tokens(gen, batch_indices, prompt_tokens)

    while True:
        prompt = console.input("Prompt: ")

        if prompt == "/clear":
            gen = reset_generation_state(gen)
            continue

        text = [[{"role": "user", "content": prompt}] for _ in range(batch_size)]
        prompt_tokens = encode_input(tokenizer, text)

        start_time = time.time()
        start_tokens = gen.kv_cache_length[0].item()
        append_prompt_tokens(np_gen, batch_indices, prompt_tokens)
        gen = update_gen_state(gen, np_gen)
        gen: GenerationState = generate(model_def, model_state, "simple", gen)
        np_gen = convert_to_np(gen)

        end_tokens = gen.kv_cache_length[0].item()
        end_time = time.time()

        _, output_text = decode_responses(tokenizer, np_gen)
        console.print("--------")
        console.print(Markdown(output_text[0]))
        console.print(
            f"TPS: {(end_tokens - start_tokens) / (end_time - start_time):.2f}"
        )


def main():
    from vaml.base_model_loader import load_base_model

    console = Console()

    rngs = nnx.Rngs(0)
    model, tokenizer, sampling = load_base_model("Qwen/Qwen3-4B-Instruct-2507", rngs)

    chat(
        console,
        model,
        tokenizer,
        sampling,
        batch_size=1,
        seq_length=1024,
        rngs=rngs,
    )


if __name__ == "__main__":
    main()
